### ISSUE TITLE
Clarify layerProtocolName attributes in ConnectivityService, ServicePort and ConnectivtyConstraint.

### ISSUE THREAD

**Issue by HuiDingCATR** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#130]
In reviewing the OIF test specs, which is based on TAPI IM, redundant layerProtocolName is found.

**Comment by HuiDingCATR** [comment]
In transport API call on Oct. 18, Karthik suggested layerProtocolName should exist. The name of this attribute maybe changed to differentiate from layerProtocolName in ServicePort, connConstraints.

**Comment by italobusi** [comment]
I would like to understand how this attribute is intended to be used.

Let's consider as an example the 10GE EPL service described in section 5.1 of TR-527. In order to support this service, the network can instantiate either on ODU2 connection or a PW connection (let's not consider the option for an S-EC connection since I have some doubts about how sub-layering is managed with T-API).

If the client is interested to select which option, the server can expose a topology view which have at least one ODU node (representing the whole ODU network), one MPLS-TP node (representing the whole MPLS-TP network) and one ETH node (representing the edge nodes) as well as transitional links between the ETH node and the ODU and MPLS-TP nodes.

In this way the client:
a) knows that both ODU and MPLS-TP server layers are available
b) can use path constraints to influence the decision about which server layer to use

What is the added value of the layerProtocolName attributed in the ConnectivityService?

What happens if the layerProtocolName is set to ODU and the path constraints request to avoid the TL between ETH and ODU nodes?

**Comment by karthik-sethuraman** [comment]
The following was original intended usage for layerProtocol(Name) in various ConnectivityConstructs:
- ServiceEndPoint – has LayerProtocol list for the provider to be able to advertise layer/technology specific attributes/capabilties – this is read-only over TAPI interface
- ConnectivityService – layerProtocolName – layer of the ConnectvityService being requested by TAPI client 
- ServicePort – layerProtocolName – needed when at least one of the ServiceEndpoints advertise/supports multiple layers – e.g ETH + ODU or OCH
- ConnectivityConstraints – preferredTransportLayer – list – soft constraint requested by client to indicate the layer(s) of transport connection that it prefers to carry the service. This could be same as the service layer or one of the supported server layers

**Comment by karthik-sethuraman** [comment]
Fixed by #173
